version: '3'
services:
    faker:
        build: .
        ports:
            - "3001:3001"
        environment:
            FAKER_PATH: /tmp/restFolder
            URL_PATH: "/faker"
        volumes: 
            - ./rest:/tmp/restFolder